name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd backend_vercel

            echo "📥 Pull latest code"
            git pull origin main

            echo "📦 Install deps"
            npm install

            echo "⚙️ Create .env file"
            cat <<EOF > .env
            DB_URL=${{ secrets.DB_URL }}
            PORT=3000
            USERNAME="shaik849"
            EOF

            echo "🏗️ Build TS"
            npm run build

            echo "🔄 Restart PM2"
            pm2 delete backend || true
            pm2 start dist/index.js --name backend

            pm2 save